### ISSUE TITLE
Perfect Test Environment at HQ

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/documentation#16]
Take our current test environment and have all the Bridges report to a Private Archivist to have contained data sets for new component and algorithm testing.

**Comment by maryannxy** [comment]
@arietrouw When would you like for this to be complete?

**Comment by arietrouw** [comment]
I think it will benefit us very much.  I think we need to wait for some of the Boston Sprint stuff to be complete, so lets do it during Chicago, almost as a validation of success of the Boston Sprint.
