### ISSUE TITLE
Verify Badges and ReadMe files

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/documentation#7]
Make sure all the readme files are up to date for the following repos as per our company template.

Make sure all Badges are configured for all repos as per the following standard

Badges for all NodeJS/React/Bootstrap repos:

BetterCodeHub
SonarQube
CodeClimate
Codacy
DepShield
David-dm
Travis-CI
Nodei.com (NPM)

Badges for iOS/OSX/Swift repos:

BetterCodeHub
SonarQube
CodeClimate
Codacy
Travis-ci
CocoaPod

Badges for Android/Kotlin/Java repos:

BetterCodeHub
SonarQube
CodeClimate
Codacy
DepShield
Travis-ci
JitPack

Badges for C/Firmware repos:
(not sure if all these are possible)

BetterCodeHub
SonarQube
CodeClimate
Codacy
Travis-ci

**Comment by pllearns** [comment]
replaced by multiple issues
